// Wrap: .NET monads.
// Copyright (c) bfren - licensed under https://mit.bfren.dev/2019

using System;
using System.Threading.Tasks;

namespace Wrap.Extensions;

public static partial class MaybeExtensions
{
	/// <summary>
	/// Return a value determined by the value of <paramref name="this"/> and the result of <paramref name="predicate"/>.
	/// </summary>
	/// <typeparam name="T">Some value type.</typeparam>
	/// <typeparam name="TReturn">Return value type.</typeparam>
	/// <param name="this">Maybe object.</param>
	/// <param name="predicate">Uses value of <paramref name="this"/> to use <paramref name="f"/> or return a Failure object.</param>
	/// <param name="f">Used if <paramref name="this"/> is <see cref="Ok{T}"/> and <paramref name="predicate"/> returns <see langword="true"/>.</param>
	/// <returns>Value generated by <paramref name="f"/>, or a Failure object.</returns>
	public static Maybe<TReturn> BindIf<T, TReturn>(this Maybe<T> @this, Func<T, bool> predicate, Func<T, Maybe<TReturn>> f) =>
		Bind(@this,
			x => predicate(x) switch
			{
				false =>
					M.None,

				true =>
					f(x)
			}
		);

	/// <inheritdoc cref="BindIf{T, TReturn}(Maybe{T}, Func{T, bool}, Func{T, Maybe{TReturn}})"/>
	public static Task<Maybe<TReturn>> BindIfAsync<T, TReturn>(this Maybe<T> @this, Func<T, bool> predicate, Func<T, Task<Maybe<TReturn>>> f) =>
		BindIfAsync(@this.AsTask(), x => Task.FromResult(predicate(x)), f);

	/// <inheritdoc cref="BindIf{T, TReturn}(Maybe{T}, Func{T, bool}, Func{T, Maybe{TReturn}})"/>
	public static Task<Maybe<TReturn>> BindIfAsync<T, TReturn>(this Maybe<T> @this, Func<T, Task<bool>> predicate, Func<T, Task<Maybe<TReturn>>> f) =>
		BindIfAsync(@this.AsTask(), predicate, f);

	/// <inheritdoc cref="BindIf{T, TReturn}(Maybe{T}, Func{T, bool}, Func{T, Maybe{TReturn}})"/>
	public static Task<Maybe<TReturn>> BindIfAsync<T, TReturn>(this Task<Maybe<T>> @this, Func<T, bool> predicate, Func<T, Maybe<TReturn>> f) =>
		BindIfAsync(@this, x => Task.FromResult(predicate(x)), x => f(x).AsTask());

	/// <inheritdoc cref="BindIf{T, TReturn}(Maybe{T}, Func{T, bool}, Func{T, Maybe{TReturn}})"/>
	public static Task<Maybe<TReturn>> BindIfAsync<T, TReturn>(this Task<Maybe<T>> @this, Func<T, Task<bool>> predicate, Func<T, Maybe<TReturn>> f) =>
		BindIfAsync(@this, predicate, x => f(x).AsTask());

	/// <inheritdoc cref="BindIf{T, TReturn}(Maybe{T}, Func{T, bool}, Func{T, Maybe{TReturn}})"/>
	public static async Task<Maybe<TReturn>> BindIfAsync<T, TReturn>(this Task<Maybe<T>> @this, Func<T, Task<bool>> predicate, Func<T, Task<Maybe<TReturn>>> f) =>
		await BindAsync(@this,
			async x => await predicate(x) switch
			{
				false =>
					M.None,

				true =>
					await f(x)
			}
		);
}
