// Wrap: .NET monads.
// Copyright (c) bfren - licensed under https://mit.bfren.dev/2019

using System;
using System.Threading.Tasks;

namespace Wrap.Extensions;

public static partial class MaybeExtensions
{
	/// <summary>
	/// Return a value determined by the value of <paramref name="this"/> and the result of <paramref name="fTest"/>.
	/// </summary>
	/// <typeparam name="T">Ok value type.</typeparam>
	/// <typeparam name="TReturn">Return value type.</typeparam>
	/// <param name="this">Maybe object.</param>
	/// <param name="fTest">Uses value of <paramref name="this"/> to determines whether <paramref name="fFalse"/> or <paramref name="fTrue"/> should be used.</param>
	/// <param name="fTrue">Used if <paramref name="this"/> is <see cref="Ok{T}"/> and <paramref name="fTest"/> returns <see langword="true"/>.</param>
	/// <param name="fFalse">Used if <paramref name="this"/> is <see cref="Ok{T}"/> and <paramref name="fTest"/> returns <see langword="false"/>.</param>
	/// <returns>Value generated by<paramref name="fFalse"/> or <paramref name="fTrue"/>.</returns>
	public static Maybe<TReturn> If<T, TReturn>(this Maybe<T> @this, Func<T, bool> fTest, Func<T, Maybe<TReturn>> fTrue, Func<T, Maybe<TReturn>> fFalse) =>
		Bind(@this,
			x => fTest(x) switch
			{
				false =>
					fFalse(x),

				true =>
					fTrue(x)
			}
		);

	/// <inheritdoc cref="If{T, TReturn}(Maybe{T}, Func{T, bool}, Func{T, Maybe{TReturn}}, Func{T, Maybe{TReturn}})"/>
	public static Task<Maybe<TReturn>> IfAsync<T, TReturn>(this Maybe<T> @this, Func<T, bool> fTest, Func<T, Task<Maybe<TReturn>>> fTrue, Func<T, Task<Maybe<TReturn>>> fFalse) =>
		IfAsync(@this.AsTask(), fTest, fTrue, fFalse);

	/// <inheritdoc cref="If{T, TReturn}(Maybe{T}, Func{T, bool}, Func{T, Maybe{TReturn}}, Func{T, Maybe{TReturn}})"/>
	public static Task<Maybe<TReturn>> IfAsync<T, TReturn>(this Task<Maybe<T>> @this, Func<T, bool> fTest, Func<T, Maybe<TReturn>> fTrue, Func<T, Maybe<TReturn>> fFalse) =>
		IfAsync(@this, fTest, async x => fTrue(x), async x => fFalse(x));

	/// <inheritdoc cref="If{T, TReturn}(Maybe{T}, Func{T, bool}, Func{T, Maybe{TReturn}}, Func{T, Maybe{TReturn}})"/>
	public static Task<Maybe<TReturn>> IfAsync<T, TReturn>(this Task<Maybe<T>> @this, Func<T, bool> fTest, Func<T, Task<Maybe<TReturn>>> fTrue, Func<T, Task<Maybe<TReturn>>> fFalse) =>
		BindAsync(@this,
			x => fTest(x) switch
			{
				false =>
					fFalse(x),

				true =>
					fTrue(x)
			}
		);

	#region Special Case - Act if True

	/// <summary>
	/// Return a value determined by the value of <paramref name="this"/> and the result of <paramref name="fTest"/>.
	/// </summary>
	/// <typeparam name="T">Ok value type.</typeparam>
	/// <param name="this">Maybe object.</param>
	/// <param name="fTest">Uses value of <paramref name="this"/> to determin whether to return <paramref name="fTrue"/> or original value.</param>
	/// <param name="fTrue">Used if <paramref name="this"/> is <see cref="Ok{T}"/> and <paramref name="fTest"/> returns <see langword="true"/>.</param>
	/// <returns>Value generated by <paramref name="fTrue"/> or original value if <paramref name="fTest"/> is false.</returns>
	public static Maybe<T> If<T>(this Maybe<T> @this, Func<T, bool> fTest, Func<T, Maybe<T>> fTrue) =>
		If(@this, fTest, fTrue, x => x);

	/// <inheritdoc cref="If{T}(Maybe{T}, Func{T, bool}, Func{T, Maybe{T}})"/>
	public static Task<Maybe<T>> IfAsync<T>(this Maybe<T> @this, Func<T, bool> fTest, Func<T, Task<Maybe<T>>> fTrue) =>
		IfAsync(@this.AsTask(), fTest, fTrue, async x => x);

	/// <inheritdoc cref="If{T}(Maybe{T}, Func{T, bool}, Func{T, Maybe{T}})"/>
	public static Task<Maybe<T>> IfAsync<T>(this Task<Maybe<T>> @this, Func<T, bool> fTest, Func<T, Maybe<T>> fTrue) =>
		IfAsync(@this, fTest, async x => fTrue(x), async x => x);

	/// <inheritdoc cref="If{T}(Maybe{T}, Func{T, bool}, Func{T, Maybe{T}})"/>
	public static Task<Maybe<T>> IfAsync<T>(this Task<Maybe<T>> @this, Func<T, bool> fTest, Func<T, Task<Maybe<T>>> fTrue) =>
		IfAsync(@this, fTest, fTrue, async x => x);

	#endregion

	#region Special Case - Act if False

	/// <summary>
	/// Return a value determined by the value of <paramref name="this"/> and the result of <paramref name="fTest"/>.
	/// </summary>
	/// <typeparam name="T">Ok value type.</typeparam>
	/// <param name="this">Maybe object.</param>
	/// <param name="fTest">Uses value of <paramref name="this"/> if <paramref name="this"/> is <see cref="Ok{T}"/>.</param>
	/// <param name="fFalse">Used if <paramref name="this"/> is <see cref="Ok{T}"/> and <paramref name="fTest"/> returns <see langword="false"/>.</param>
	/// <returns>Original value or value generated by<paramref name="fFalse"/>.</returns>
	public static Maybe<T> IfNot<T>(this Maybe<T> @this, Func<T, bool> fTest, Func<T, Maybe<T>> fFalse) =>
		If(@this, fTest, x => x, fFalse);

	/// <inheritdoc cref="IfNot{T}(Maybe{T}, Func{T, bool}, Func{T, Maybe{T}})"/>
	public static Task<Maybe<T>> IfNotAsync<T>(this Maybe<T> @this, Func<T, bool> fTest, Func<T, Task<Maybe<T>>> fFalse) =>
		IfAsync(@this.AsTask(), fTest, async x => x, fFalse);

	/// <inheritdoc cref="IfNot{T}(Maybe{T}, Func{T, bool}, Func{T, Maybe{T}})"/>
	public static Task<Maybe<T>> IfNotAsync<T>(this Task<Maybe<T>> @this, Func<T, bool> fTest, Func<T, Maybe<T>> fFalse) =>
		IfAsync(@this, fTest, async x => x, async x => fFalse(x));

	/// <inheritdoc cref="IfNot{T}(Maybe{T}, Func{T, bool}, Func{T, Maybe{T}})"/>
	public static Task<Maybe<T>> ContinueIfAsync<T>(this Task<Maybe<T>> @this, Func<T, bool> fTest, Func<T, Task<Maybe<T>>> fFalse) =>
		IfAsync(@this, fTest, async x => x, fFalse);

	#endregion
}
