// Wrap: .NET monads.
// Copyright (c) bfren - licensed under https://mit.bfren.dev/2019

using System;
using System.Threading.Tasks;

namespace Wrap.Extensions;

public static partial class MaybeExtensions
{
	/// <summary>
	/// Return a value determined by the value of <paramref name="this"/> and the result of <paramref name="fTest"/>.
	/// </summary>
	/// <typeparam name="T">Ok value type.</typeparam>
	/// <typeparam name="TReturn">Return value type.</typeparam>
	/// <param name="this">Maybe object.</param>
	/// <param name="fTest">Uses value of <paramref name="this"/> to use <paramref name="f"/> or return a Failure object.</param>
	/// <param name="f">Used if <paramref name="this"/> is <see cref="Ok{T}"/> and <paramref name="fTest"/> returns <see langword="true"/>.</param>
	/// <returns>Value generated by <paramref name="f"/>, or a Failure object.</returns>
	public static Maybe<TReturn> MapIf<T, TReturn>(this Maybe<T> @this, Func<T, bool> fTest, Func<T, TReturn> f) =>
		If(@this, fTest, x => M.Wrap(f(x)), _ => M.None);

	/// <inheritdoc cref="MapIf{T, TReturn}(Maybe{T}, Func{T, bool}, Func{T, TReturn})"/>
	public static Task<Maybe<TReturn>> MapIfAsync<T, TReturn>(this Maybe<T> @this, Func<T, bool> fTest, Func<T, Task<TReturn>> f) =>
		MapIfAsync(@this.AsTask(), fTest, f);

	/// <inheritdoc cref="MapIf{T, TReturn}(Maybe{T}, Func{T, bool}, Func{T, TReturn})"/>
	public static Task<Maybe<TReturn>> MapIfAsync<T, TReturn>(this Task<Maybe<T>> @this, Func<T, bool> fTest, Func<T, TReturn> f) =>
		MapIfAsync(@this, fTest, async x => f(x));

	/// <inheritdoc cref="MapIf{T, TReturn}(Maybe{T}, Func{T, bool}, Func{T, TReturn})"/>
	public static Task<Maybe<TReturn>> MapIfAsync<T, TReturn>(this Task<Maybe<T>> @this, Func<T, bool> fTest, Func<T, Task<TReturn>> f) =>
		IfAsync(@this, fTest, async x => M.Wrap(await f(x)), async _ => M.None);
}
