// Wrap: Functional Monads for .NET
// Copyright (c) bfren - licensed under https://mit.bfren.dev/2019

using System;
using System.Threading.Tasks;

namespace Wrap.Extensions;

public static partial class MaybeExtensions
{
	/// <summary>
	/// Return a value determined by the value of <paramref name="this"/> and the result of <paramref name="fTest"/>.
	/// </summary>
	/// <typeparam name="T">Some value type.</typeparam>
	/// <typeparam name="TReturn">Return value type.</typeparam>
	/// <param name="this">Maybe object.</param>
	/// <param name="fTest">Uses value of <paramref name="this"/> to use <paramref name="f"/> or return a Failure object.</param>
	/// <param name="f">Used if <paramref name="this"/> is <see cref="Ok{T}"/> and <paramref name="fTest"/> returns <see langword="true"/>.</param>
	/// <returns>Value generated by <paramref name="f"/>, or a Failure object.</returns>
	public static Maybe<TReturn> BindIf<T, TReturn>(this Maybe<T> @this, Func<T, bool> fTest, Func<T, Maybe<TReturn>> f) =>
		If(@this, fTest, f, _ => M.None);

	/// <inheritdoc cref="BindIf{T, TReturn}(Maybe{T}, Func{T, bool}, Func{T, Maybe{TReturn}})"/>
	public static Task<Maybe<TReturn>> BindIfAsync<T, TReturn>(this Maybe<T> @this, Func<T, bool> fTest, Func<T, Task<Maybe<TReturn>>> f) =>
		BindIfAsync(@this.AsTask(), fTest, f);

	/// <inheritdoc cref="BindIf{T, TReturn}(Maybe{T}, Func{T, bool}, Func{T, Maybe{TReturn}})"/>
	public static Task<Maybe<TReturn>> BindIfAsync<T, TReturn>(this Task<Maybe<T>> @this, Func<T, bool> fTest, Func<T, Maybe<TReturn>> f) =>
		BindIfAsync(@this, fTest, async x => f(x));

	/// <inheritdoc cref="BindIf{T, TReturn}(Maybe{T}, Func{T, bool}, Func{T, Maybe{TReturn}})"/>
	public static Task<Maybe<TReturn>> BindIfAsync<T, TReturn>(this Task<Maybe<T>> @this, Func<T, bool> fTest, Func<T, Task<Maybe<TReturn>>> f) =>
		IfAsync(@this, fTest, f, async _ => M.None);
}
