// Wrap: .NET monads.
// Copyright (c) bfren - licensed under https://mit.bfren.dev/2019

using System;
using System.Threading.Tasks;

namespace Wrap.Extensions;

public static partial class MaybeExtensions
{
	/// <summary>
	/// Return a value determined by the value of <paramref name="this"/> and the result of <paramref name="fTest"/>.
	/// </summary>
	/// <typeparam name="T">Some value type.</typeparam>
	/// <typeparam name="TReturn">Return value type.</typeparam>
	/// <param name="this">Maybe object.</param>
	/// <param name="fNone">Function to return a value if <paramref name="this"/> is <see cref="None"/>.</param>
	/// <param name="fTest">Uses value of <paramref name="this"/> to determines whether <paramref name="fFalse"/> or <paramref name="fTrue"/> should be used.</param>
	/// <param name="fFalse">Used if <paramref name="this"/> is <see cref="Some{T}"/> and <paramref name="fTest"/> returns <see langword="false"/>.</param>
	/// <param name="fTrue">Used if <paramref name="this"/> is <see cref="Some{T}"/> and <paramref name="fTest"/> returns <see langword="true"/>.</param>
	/// <returns>Value generated by <paramref name="fNone"/>, <paramref name="fFalse"/> or <paramref name="fTrue"/>.</returns>
	public static TReturn MatchIf<T, TReturn>(this Maybe<T> @this,
		Func<TReturn> fNone,
		Func<T, bool> fTest,
		Func<T, TReturn> fFalse,
		Func<T, TReturn> fTrue
	) =>
		Match(@this,
			fNone: fNone,
			fSome: x => fTest(x) switch
			{
				false =>
					fFalse(x),

				true =>
					fTrue(x)
			}
		);

	/// <inheritdoc cref="MatchIf{T, TReturn}(Maybe{T}, Func{TReturn}, Func{T, bool}, Func{T, TReturn}, Func{T, TReturn})"/>
	public static Task<TReturn> MatchIfAsync<T, TReturn>(this Maybe<T> @this,
		Func<TReturn> fNone,
		Func<T, bool> fTest,
		Func<T, Task<TReturn>> fFalse,
		Func<T, TReturn> fTrue
	) =>
		MatchIfAsync(Task.FromResult(@this),
			fNone: async () => fNone(),
			fTest: async x => fTest(x),
			fFalse: fFalse,
			fTrue: async x => fTrue(x)
		);

	/// <inheritdoc cref="MatchIf{T, TReturn}(Maybe{T}, Func{TReturn}, Func{T, bool}, Func{T, TReturn}, Func{T, TReturn})"/>
	public static Task<TReturn> MatchIfAsync<T, TReturn>(this Maybe<T> @this,
		Func<TReturn> fNone,
		Func<T, bool> fTest,
		Func<T, TReturn> fFalse,
		Func<T, Task<TReturn>> fTrue
	) =>
		MatchIfAsync(Task.FromResult(@this),
			fNone: async () => fNone(),
			fTest: async x => fTest(x),
			fFalse: async x => fFalse(x),
			fTrue: fTrue
		);

	/// <inheritdoc cref="MatchIf{T, TReturn}(Maybe{T}, Func{TReturn}, Func{T, bool}, Func{T, TReturn}, Func{T, TReturn})"/>
	public static Task<TReturn> MatchIfAsync<T, TReturn>(this Maybe<T> @this,
		Func<TReturn> fNone,
		Func<T, bool> fTest,
		Func<T, Task<TReturn>> fFalse,
		Func<T, Task<TReturn>> fTrue
	) =>
		MatchIfAsync(Task.FromResult(@this),
			fNone: async () => fNone(),
			fTest: async x => fTest(x),
			fFalse: fFalse,
			fTrue: fTrue
		);

	/// <inheritdoc cref="MatchIf{T, TReturn}(Maybe{T}, Func{TReturn}, Func{T, bool}, Func{T, TReturn}, Func{T, TReturn})"/>
	public static Task<TReturn> MatchIfAsync<T, TReturn>(this Maybe<T> @this,
		Func<TReturn> fNone,
		Func<T, Task<bool>> fTest,
		Func<T, TReturn> fFalse,
		Func<T, TReturn> fTrue
	) =>
		MatchIfAsync(Task.FromResult(@this),
			fNone: async () => fNone(),
			fTest: fTest,
			fFalse: async x => fFalse(x),
			fTrue: async x => fTrue(x)
		);

	/// <inheritdoc cref="MatchIf{T, TReturn}(Maybe{T}, Func{TReturn}, Func{T, bool}, Func{T, TReturn}, Func{T, TReturn})"/>
	public static Task<TReturn> MatchIfAsync<T, TReturn>(this Maybe<T> @this,
		Func<TReturn> fNone,
		Func<T, Task<bool>> fTest,
		Func<T, Task<TReturn>> fFalse,
		Func<T, TReturn> fTrue
	) =>
		MatchIfAsync(Task.FromResult(@this),
			fNone: async () => fNone(),
			fTest: fTest,
			fFalse: fFalse,
			fTrue: async x => fTrue(x)
		);

	/// <inheritdoc cref="MatchIf{T, TReturn}(Maybe{T}, Func{TReturn}, Func{T, bool}, Func{T, TReturn}, Func{T, TReturn})"/>
	public static Task<TReturn> MatchIfAsync<T, TReturn>(this Maybe<T> @this,
		Func<TReturn> fNone,
		Func<T, Task<bool>> fTest,
		Func<T, TReturn> fFalse,
		Func<T, Task<TReturn>> fTrue
	) =>
		MatchIfAsync(Task.FromResult(@this),
			fNone: async () => fNone(),
			fTest: fTest,
			fFalse: async x => fFalse(x),
			fTrue: fTrue
		);

	/// <inheritdoc cref="MatchIf{T, TReturn}(Maybe{T}, Func{TReturn}, Func{T, bool}, Func{T, TReturn}, Func{T, TReturn})"/>
	public static Task<TReturn> MatchIfAsync<T, TReturn>(this Maybe<T> @this,
		Func<TReturn> fNone,
		Func<T, Task<bool>> fTest,
		Func<T, Task<TReturn>> fFalse,
		Func<T, Task<TReturn>> fTrue
	) =>
		MatchIfAsync(Task.FromResult(@this),
			fNone: async () => fNone(),
			fTest: fTest,
			fFalse: fFalse,
			fTrue: fTrue
		);

	/// <inheritdoc cref="MatchIf{T, TReturn}(Maybe{T}, Func{TReturn}, Func{T, bool}, Func{T, TReturn}, Func{T, TReturn})"/>
	public static Task<TReturn> MatchIfAsync<T, TReturn>(this Task<Maybe<T>> @this,
		Func<TReturn> fNone,
		Func<T, bool> fTest,
		Func<T, TReturn> fFalse,
		Func<T, TReturn> fTrue
	) =>
		MatchIfAsync(@this,
			fNone: async () => fNone(),
			fTest: async x => fTest(x),
			fFalse: async x => fFalse(x),
			fTrue: async x => fTrue(x)
		);

	/// <inheritdoc cref="MatchIf{T, TReturn}(Maybe{T}, Func{TReturn}, Func{T, bool}, Func{T, TReturn}, Func{T, TReturn})"/>
	public static Task<TReturn> MatchIfAsync<T, TReturn>(this Task<Maybe<T>> @this,
		Func<TReturn> fNone,
		Func<T, bool> fTest,
		Func<T, Task<TReturn>> fFalse,
		Func<T, TReturn> fTrue
	) =>
		MatchIfAsync(@this,
			fNone: async () => fNone(),
			fTest: async x => fTest(x),
			fFalse: fFalse,
			fTrue: async x => fTrue(x)
		);

	/// <inheritdoc cref="MatchIf{T, TReturn}(Maybe{T}, Func{TReturn}, Func{T, bool}, Func{T, TReturn}, Func{T, TReturn})"/>
	public static Task<TReturn> MatchIfAsync<T, TReturn>(this Task<Maybe<T>> @this,
		Func<TReturn> fNone,
		Func<T, bool> fTest,
		Func<T, TReturn> fFalse,
		Func<T, Task<TReturn>> fTrue
	) =>
		MatchIfAsync(@this,
			fNone: async () => fNone(),
			fTest: async x => fTest(x),
			fFalse: async x => fFalse(x),
			fTrue: fTrue
		);

	/// <inheritdoc cref="MatchIf{T, TReturn}(Maybe{T}, Func{TReturn}, Func{T, bool}, Func{T, TReturn}, Func{T, TReturn})"/>
	public static Task<TReturn> MatchIfAsync<T, TReturn>(this Task<Maybe<T>> @this,
		Func<TReturn> fNone,
		Func<T, bool> fTest,
		Func<T, Task<TReturn>> fFalse,
		Func<T, Task<TReturn>> fTrue
	) =>
		MatchIfAsync(@this,
			fNone: async () => fNone(),
			fTest: async x => fTest(x),
			fFalse: fFalse,
			fTrue: fTrue
		);

	/// <inheritdoc cref="MatchIf{T, TReturn}(Maybe{T}, Func{TReturn}, Func{T, bool}, Func{T, TReturn}, Func{T, TReturn})"/>
	public static Task<TReturn> MatchIfAsync<T, TReturn>(this Task<Maybe<T>> @this,
		Func<TReturn> fNone,
		Func<T, Task<bool>> fTest,
		Func<T, TReturn> fFalse,
		Func<T, TReturn> fTrue
	) =>
		MatchIfAsync(@this,
			fNone: async () => fNone(),
			fTest: fTest,
			fFalse: async x => fFalse(x),
			fTrue: async x => fTrue(x)
		);

	/// <inheritdoc cref="MatchIf{T, TReturn}(Maybe{T}, Func{TReturn}, Func{T, bool}, Func{T, TReturn}, Func{T, TReturn})"/>
	public static Task<TReturn> MatchIfAsync<T, TReturn>(this Task<Maybe<T>> @this,
		Func<TReturn> fNone,
		Func<T, Task<bool>> fTest,
		Func<T, Task<TReturn>> fFalse,
		Func<T, TReturn> fTrue
	) =>
		MatchIfAsync(@this,
			fNone: async () => fNone(),
			fTest: fTest,
			fFalse: fFalse,
			fTrue: async x => fTrue(x)
		);

	/// <inheritdoc cref="MatchIf{T, TReturn}(Maybe{T}, Func{TReturn}, Func{T, bool}, Func{T, TReturn}, Func{T, TReturn})"/>
	public static Task<TReturn> MatchIfAsync<T, TReturn>(this Task<Maybe<T>> @this,
		Func<TReturn> fNone,
		Func<T, Task<bool>> fTest,
		Func<T, TReturn> fFalse,
		Func<T, Task<TReturn>> fTrue
	) =>
		MatchIfAsync(@this,
			fNone: async () => fNone(),
			fTest: fTest,
			fFalse: async x => fFalse(x),
			fTrue: fTrue
		);

	/// <inheritdoc cref="MatchIf{T, TReturn}(Maybe{T}, Func{TReturn}, Func{T, bool}, Func{T, TReturn}, Func{T, TReturn})"/>
	public static Task<TReturn> MatchIfAsync<T, TReturn>(this Maybe<T> @this,
		Func<Task<TReturn>> fNone,
		Func<T, bool> fTest,
		Func<T, TReturn> fFalse,
		Func<T, TReturn> fTrue
	) =>
		MatchIfAsync(Task.FromResult(@this),
			fNone: fNone,
			fTest: async x => fTest(x),
			fFalse: async x => fFalse(x),
			fTrue: async x => fTrue(x)
		);

	/// <inheritdoc cref="MatchIf{T, TReturn}(Maybe{T}, Func{TReturn}, Func{T, bool}, Func{T, TReturn}, Func{T, TReturn})"/>
	public static Task<TReturn> MatchIfAsync<T, TReturn>(this Maybe<T> @this,
		Func<Task<TReturn>> fNone,
		Func<T, bool> fTest,
		Func<T, Task<TReturn>> fFalse,
		Func<T, TReturn> fTrue
	) =>
		MatchIfAsync(Task.FromResult(@this),
			fNone: fNone,
			fTest: async x => fTest(x),
			fFalse: fFalse,
			fTrue: async x => fTrue(x)
		);

	/// <inheritdoc cref="MatchIf{T, TReturn}(Maybe{T}, Func{TReturn}, Func{T, bool}, Func{T, TReturn}, Func{T, TReturn})"/>
	public static Task<TReturn> MatchIfAsync<T, TReturn>(this Maybe<T> @this,
		Func<Task<TReturn>> fNone,
		Func<T, bool> fTest,
		Func<T, TReturn> fFalse,
		Func<T, Task<TReturn>> fTrue
	) =>
		MatchIfAsync(Task.FromResult(@this),
			fNone: fNone,
			fTest: async x => fTest(x),
			fFalse: async x => fFalse(x),
			fTrue: fTrue
		);

	/// <inheritdoc cref="MatchIf{T, TReturn}(Maybe{T}, Func{TReturn}, Func{T, bool}, Func{T, TReturn}, Func{T, TReturn})"/>
	public static Task<TReturn> MatchIfAsync<T, TReturn>(this Maybe<T> @this,
		Func<Task<TReturn>> fNone,
		Func<T, bool> fTest,
		Func<T, Task<TReturn>> fFalse,
		Func<T, Task<TReturn>> fTrue
	) =>
		MatchIfAsync(Task.FromResult(@this),
			fNone: fNone,
			fTest: async x => fTest(x),
			fFalse: fFalse,
			fTrue: fTrue
		);

	/// <inheritdoc cref="MatchIf{T, TReturn}(Maybe{T}, Func{TReturn}, Func{T, bool}, Func{T, TReturn}, Func{T, TReturn})"/>
	public static Task<TReturn> MatchIfAsync<T, TReturn>(this Maybe<T> @this,
		Func<Task<TReturn>> fNone,
		Func<T, Task<bool>> fTest,
		Func<T, TReturn> fFalse,
		Func<T, TReturn> fTrue
	) =>
		MatchIfAsync(Task.FromResult(@this),
			fNone: fNone,
			fTest: fTest,
			fFalse: async x => fFalse(x),
			fTrue: async x => fTrue(x)
		);

	/// <inheritdoc cref="MatchIf{T, TReturn}(Maybe{T}, Func{TReturn}, Func{T, bool}, Func{T, TReturn}, Func{T, TReturn})"/>
	public static Task<TReturn> MatchIfAsync<T, TReturn>(this Maybe<T> @this,
		Func<Task<TReturn>> fNone,
		Func<T, Task<bool>> fTest,
		Func<T, Task<TReturn>> fFalse,
		Func<T, TReturn> fTrue
	) =>
		MatchIfAsync(Task.FromResult(@this),
			fNone: fNone,
			fTest: fTest,
			fFalse: fFalse,
			fTrue: async x => fTrue(x)
		);

	/// <inheritdoc cref="MatchIf{T, TReturn}(Maybe{T}, Func{TReturn}, Func{T, bool}, Func{T, TReturn}, Func{T, TReturn})"/>
	public static Task<TReturn> MatchIfAsync<T, TReturn>(this Maybe<T> @this,
		Func<Task<TReturn>> fNone,
		Func<T, Task<bool>> fTest,
		Func<T, TReturn> fFalse,
		Func<T, Task<TReturn>> fTrue
	) =>
		MatchIfAsync(Task.FromResult(@this),
			fNone: fNone,
			fTest: fTest,
			fFalse: async x => fFalse(x),
			fTrue: fTrue
		);

	/// <inheritdoc cref="MatchIf{T, TReturn}(Maybe{T}, Func{TReturn}, Func{T, bool}, Func{T, TReturn}, Func{T, TReturn})"/>
	public static Task<TReturn> MatchIfAsync<T, TReturn>(this Maybe<T> @this,
		Func<Task<TReturn>> fNone,
		Func<T, Task<bool>> fTest,
		Func<T, Task<TReturn>> fFalse,
		Func<T, Task<TReturn>> fTrue
	) =>
		MatchIfAsync(Task.FromResult(@this),
			fNone: fNone,
			fTest: fTest,
			fFalse: fFalse,
			fTrue: fTrue
		);

	/// <inheritdoc cref="MatchIf{T, TReturn}(Maybe{T}, Func{TReturn}, Func{T, bool}, Func{T, TReturn}, Func{T, TReturn})"/>
	public static Task<TReturn> MatchIfAsync<T, TReturn>(this Task<Maybe<T>> @this,
		Func<Task<TReturn>> fNone,
		Func<T, bool> fTest,
		Func<T, TReturn> fFalse,
		Func<T, TReturn> fTrue
	) =>
		MatchIfAsync(@this,
			fNone: fNone,
			fTest: async x => fTest(x),
			fFalse: async x => fFalse(x),
			fTrue: async x => fTrue(x)
		);

	/// <inheritdoc cref="MatchIf{T, TReturn}(Maybe{T}, Func{TReturn}, Func{T, bool}, Func{T, TReturn}, Func{T, TReturn})"/>
	public static Task<TReturn> MatchIfAsync<T, TReturn>(this Task<Maybe<T>> @this,
		Func<Task<TReturn>> fNone,
		Func<T, bool> fTest,
		Func<T, Task<TReturn>> fFalse,
		Func<T, TReturn> fTrue
	) =>
		MatchIfAsync(@this,
			fNone: fNone,
			fTest: async x => fTest(x),
			fFalse: fFalse,
			fTrue: async x => fTrue(x)
		);

	/// <inheritdoc cref="MatchIf{T, TReturn}(Maybe{T}, Func{TReturn}, Func{T, bool}, Func{T, TReturn}, Func{T, TReturn})"/>
	public static Task<TReturn> MatchIfAsync<T, TReturn>(this Task<Maybe<T>> @this,
		Func<Task<TReturn>> fNone,
		Func<T, bool> fTest,
		Func<T, TReturn> fFalse,
		Func<T, Task<TReturn>> fTrue
	) =>
		MatchIfAsync(@this,
			fNone: fNone,
			fTest: async x => fTest(x),
			fFalse: async x => fFalse(x),
			fTrue: fTrue
		);

	/// <inheritdoc cref="MatchIf{T, TReturn}(Maybe{T}, Func{TReturn}, Func{T, bool}, Func{T, TReturn}, Func{T, TReturn})"/>
	public static Task<TReturn> MatchIfAsync<T, TReturn>(this Task<Maybe<T>> @this,
		Func<Task<TReturn>> fNone,
		Func<T, bool> fTest,
		Func<T, Task<TReturn>> fFalse,
		Func<T, Task<TReturn>> fTrue
	) =>
		MatchIfAsync(@this,
			fNone: fNone,
			fTest: async x => fTest(x),
			fFalse: fFalse,
			fTrue: fTrue
		);

	/// <inheritdoc cref="MatchIf{T, TReturn}(Maybe{T}, Func{TReturn}, Func{T, bool}, Func{T, TReturn}, Func{T, TReturn})"/>
	public static Task<TReturn> MatchIfAsync<T, TReturn>(this Task<Maybe<T>> @this,
		Func<Task<TReturn>> fNone,
		Func<T, Task<bool>> fTest,
		Func<T, TReturn> fFalse,
		Func<T, TReturn> fTrue
	) =>
		MatchIfAsync(@this,
			fNone: fNone,
			fTest: fTest,
			fFalse: async x => fFalse(x),
			fTrue: async x => fTrue(x)
		);

	/// <inheritdoc cref="MatchIf{T, TReturn}(Maybe{T}, Func{TReturn}, Func{T, bool}, Func{T, TReturn}, Func{T, TReturn})"/>
	public static Task<TReturn> MatchIfAsync<T, TReturn>(this Task<Maybe<T>> @this,
		Func<Task<TReturn>> fNone,
		Func<T, Task<bool>> fTest,
		Func<T, Task<TReturn>> fFalse,
		Func<T, TReturn> fTrue
	) =>
		MatchIfAsync(@this,
			fNone: fNone,
			fTest: fTest,
			fFalse: fFalse,
			fTrue: async x => fTrue(x)
		);

	/// <inheritdoc cref="MatchIf{T, TReturn}(Maybe{T}, Func{TReturn}, Func{T, bool}, Func{T, TReturn}, Func{T, TReturn})"/>
	public static Task<TReturn> MatchIfAsync<T, TReturn>(this Task<Maybe<T>> @this,
		Func<Task<TReturn>> fNone,
		Func<T, Task<bool>> fTest,
		Func<T, TReturn> fFalse,
		Func<T, Task<TReturn>> fTrue
	) =>
		MatchIfAsync(@this,
			fNone: fNone,
			fTest: fTest,
			fFalse: async x => fFalse(x),
			fTrue: fTrue
		);

	/// <inheritdoc cref="MatchIf{T, TReturn}(Maybe{T}, Func{TReturn}, Func{T, bool}, Func{T, TReturn}, Func{T, TReturn})"/>
	public static Task<TReturn> MatchIfAsync<T, TReturn>(this Task<Maybe<T>> @this,
		Func<Task<TReturn>> fNone,
		Func<T, Task<bool>> fTest,
		Func<T, Task<TReturn>> fFalse,
		Func<T, Task<TReturn>> fTrue
	) =>
		MatchAsync(@this,
			fNone: fNone,
			fSome: async x => await fTest(x) switch
			{
				false =>
					await fFalse(x),

				true =>
					await fTrue(x)
			}
		);
}
