// Wrap: .NET monads.
// Copyright (c) bfren - licensed under https://mit.bfren.dev/2019

using System;
using System.Threading.Tasks;

namespace Wrap.Extensions;

public static partial class MaybeExtensions
{
	/// <summary>
	/// Unwrap the value contained in <paramref name="this"/>.
	/// </summary>
	/// <remarks>
	/// <para>
	/// Provides access to the value wrapped by a <see cref="Maybe{T}"/> object.
	/// </para>
	/// <para>
	/// You need to provide a default value via <paramref name="fNone"/> in case
	/// <paramref name="this"/> is <see cref="None"/>.
	/// </para>
	/// </remarks>
	/// <seealso cref="UnwrapSingle{T, TSingle}(Maybe{T}, Func{TSingle})"/>
	/// <typeparam name="T">Some value type.</typeparam>
	/// <param name="this">Maybe object.</param>
	/// <param name="fNone">Function to generate a value if <paramref name="this"/> is <see cref="None"/>.</param>
	/// <returns>The value of <paramref name="this"/> or generated by <paramref name="fNone"/>.</returns>
	public static Task<T> UnwrapAsync<T>(this Maybe<T> @this, Func<Task<T>> fNone) =>
		M.MatchAsync(@this,
			fNone: fNone,
			fSome: x => x
		);

	/// <inheritdoc cref="UnwrapAsync{T}(Maybe{T}, Func{Task{T}})"/>
	public static Task<T> UnwrapAsync<T>(this Task<Maybe<T>> @this, Func<T> fNone) =>
		M.MatchAsync(@this,
			fNone: fNone,
			fSome: async x => x
		);

	/// <inheritdoc cref="UnwrapAsync{T}(Maybe{T}, Func{Task{T}})"/>
	public static Task<T> UnwrapAsync<T>(this Task<Maybe<T>> @this, Func<Task<T>> fNone) =>
		M.MatchAsync(@this,
			fNone: fNone,
			fSome: async x => x
		);
}
