// Wrap: Functional Monads for .NET
// Copyright (c) bfren - licensed under https://mit.bfren.dev/2019

using System.Linq;
using System.Text;
using System.Text.RegularExpressions;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace Wrap;

[Generator]
public sealed class FailureValueGenerator : IIncrementalGenerator
{
	public void Initialize(IncrementalGeneratorInitializationContext context)
	{
		// Filter to methods decorated with [FailureMessage]
		var methods = context.SyntaxProvider
			.ForAttributeWithMetadataName(
				"Wrap.FailureAttribute",
				predicate: static (node, _) => node is MethodDeclarationSyntax,
				transform: static (ctx, _) => GetMethodModel(ctx))
			.Where(static m => m is not null);

		context.RegisterSourceOutput(methods, static (spc, model) =>
			Execute(spc, model!));
	}

	private static MethodModel? GetMethodModel(
		GeneratorAttributeSyntaxContext ctx)
	{
		if (ctx.TargetSymbol is not IMethodSymbol method)
			return null;

		var attr = ctx.Attributes[0];

		var message = attr.ConstructorArguments[0].Value as string ?? "";
		var logLevel = attr.ConstructorArguments.Length > 1
			? (int)(attr.ConstructorArguments[1].Value ?? 0)
			: 0;

		var containingType = method.ContainingType;
		return new MethodModel
		{
			Namespace = containingType.ContainingNamespace.ToDisplayString(),
			ClassName = containingType.Name,
			MethodName = method.Name,
			Message = message,
			LogLevel = logLevel,
			Parameters = [.. method.Parameters.Select(ParameterModel.Create)],
			ReturnType = method.ReturnType.ToDisplayString()
		};
	}

	private static void Execute(SourceProductionContext ctx, MethodModel model)
	{
		var paramList = string.Join(", ",
			model.Parameters.Select(p => $"{p.Type} {p.Name}"));

		var formatArgs = model.Parameters.Length > 0 ? ", " + string.Join(", ",
			model.Parameters.Select(p => p.Name)) : "";

		// Build the interpolated message - replaces {Name} with positional args
		// matching LoggerMessage convention
		var formattedMessage = BuildMessage(model.Message, model.Parameters);

		var source = $$"""
            // <auto-generated/>
            #nullable enable

            namespace {{model.Namespace}};

            partial class {{model.ClassName}}
            {
                public static partial {{model.ReturnType}} {{model.MethodName}}({{paramList}})
                {
                    var message = {{formattedMessage}};
                    var context = "{{model.ClassName}}.{{model.MethodName}}()";
                    return new {{model.ReturnType}}(message{{formatArgs}})
                    {
                        Level = (Wrap.Logging.LogLevel){{model.LogLevel}},
                        Context = context
                    };
                }
            }
            """;

		ctx.AddSource(
			$"{model.Namespace}.{model.ClassName}.{model.MethodName}.g.cs",
			SourceText.From(source, Encoding.UTF8));
	}

	private static string BuildMessage(
		string template, ParameterModel[] parameters)
	{
		// Convert "{UserId} not found" → $"{userId} not found"
		// matching parameter names case-insensitively
		var result = template;
		foreach (var p in parameters)
		{
			// Replace {ParameterName} (case-insensitive) with the actual param
			result = Regex.Replace(
				result,
				$@"\{{{Regex.Escape(p.Name)}\}}",
				$"{{{p.Name}}}",
				RegexOptions.IgnoreCase);
		}
		return $"$\"{result}\"";
	}
}

// Models (plain records are fine here, no Roslyn types)
record MethodModel()
{
	public string Namespace { get; set; } = string.Empty;

	public string ClassName { get; set; } = string.Empty;

	public string MethodName { get; set; } = string.Empty;

	public string Message { get; set; } = string.Empty;

	public int LogLevel { get; set; }

	public ParameterModel[] Parameters { get; set; } = [];

	public string ReturnType { get; set; } = string.Empty;

}

record ParameterModel()
{
	public string Type { get; set; } = string.Empty;

	public string Name { get; set; } = string.Empty;

	public static ParameterModel Create(IParameterSymbol p) =>
		new()
		{
			Type = p.Type.ToDisplayString(),
			Name = p.Name
		};
}
