// Wrap: Functional Monads for .NET
// Copyright (c) bfren - licensed under https://mit.bfren.dev/2019

using System.Collections.Generic;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace Wrap;

[Generator]
public sealed class FailureValueGenerator : IIncrementalGenerator
{
	public void Initialize(IncrementalGeneratorInitializationContext context)
	{
		// Filter to methods decorated with [FailureMessage]
		var methods = context.SyntaxProvider
			.ForAttributeWithMetadataName(
				"Wrap.FailureAttribute",
				predicate: static (node, _) => node is MethodDeclarationSyntax,
				transform: static (ctx, _) => GetMethodModel(ctx))
			.Where(static m => m is not null);

		context.RegisterSourceOutput(methods, static (spc, model) =>
			Execute(spc, model!));
	}

	private static MethodModel? GetMethodModel(
		GeneratorAttributeSyntaxContext ctx)
	{
		if (ctx.TargetSymbol is not IMethodSymbol method)
			return null;

		var attr = ctx.Attributes[0];
		var message = attr.ConstructorArguments[0].Value as string ?? "";
		var logLevel = attr.ConstructorArguments.Length > 1
			? (int)(attr.ConstructorArguments[1].Value ?? 0)
			: 0;

		// Walk up ContainingType chain, collecting outermost → innermost
		var containingTypes = new Stack<ContainingType>();
		var current = method.ContainingType;
		while (current is not null)
		{
			var kind = current.TypeKind switch
			{
				TypeKind.Struct => "struct",
				TypeKind.Class => "class",
				_ => "class"
			};

			// Detect record — Roslyn doesn't expose it as a TypeKind
			if (current.DeclaringSyntaxReferences
					   .Select(r => r.GetSyntax())
					   .OfType<TypeDeclarationSyntax>()
					   .Any(s => s.IsKind(SyntaxKind.RecordDeclaration)
							  || s.IsKind(SyntaxKind.RecordStructDeclaration)))
			{
				kind = "record";
			}

			containingTypes.Push(new ContainingType(current.Name, kind));
			current = current.ContainingType; // null when we reach the namespace
		}


		return new MethodModel
		{
			Namespace = method.ContainingType.ContainingNamespace.ToDisplayString(),
			ClassName = method.ContainingType.Name,
			ContainingTypes = [.. containingTypes],
			MethodName = method.Name,
			Message = message,
			LogLevel = logLevel,
			Parameters = [.. method.Parameters.Select(ParameterModel.Create)],
			ReturnType = method.ReturnType.ToDisplayString()
		};
	}

	private static void Execute(SourceProductionContext ctx, MethodModel model)
	{
		var paramList = string.Join(", ", model.Parameters.Select(p => $"{p.Type} {p.Name}"));

		var argList = (model.Parameters.Length > 0) switch
		{
			true =>
				", " + string.Join(", ", model.Parameters.Select(p => p.Name)),

			false =>
				""
		};

		var sb = new StringBuilder();
		sb.AppendLine("// <auto-generated/>");
		sb.AppendLine("#nullable enable");
		sb.AppendLine();
		sb.AppendLine($"namespace {model.Namespace};");
		sb.AppendLine();

		// Open each containing type		
		for (var i = 0; i < model.ContainingTypes.Length; i++)
		{
			var indentOpen = new string(' ', 4 * i);
			var type = model.ContainingTypes[i];
			sb.AppendLine($"{indentOpen}partial {type.Kind} {type.Name}");
			sb.AppendLine($"{indentOpen}{{");
		}

		// Indent the method body one level per nesting depth
		var indent = new string(' ', model.ContainingTypes.Length * 4);

		sb.AppendLine($"{indent}public static partial {model.ReturnType} {model.MethodName}({paramList})");
		sb.AppendLine($"{indent}{{");
		sb.AppendLine($"{indent}    var message = $\"{model.Message.TrimEnd('.')}.\";");
		sb.AppendLine($"{indent}    var context = \"{model.ClassName}.{model.MethodName}()\";");
		sb.AppendLine($"{indent}    return new {model.ReturnType}(message{argList})");
		sb.AppendLine($"{indent}    {{");
		sb.AppendLine($"{indent}        Level = (Wrap.Logging.LogLevel){model.LogLevel},");
		sb.AppendLine($"{indent}        Context = context");
		sb.AppendLine($"{indent}    }};");
		sb.AppendLine($"{indent}}}");

		// Close each containing type in reverse
		for (var i = model.ContainingTypes.Length - 1; i >= 0; i--)
		{
			var indentClose = new string(' ', 4 * i);
			sb.AppendLine($"{indentClose}}}");
		}

		ctx.AddSource(
			$"{model.Namespace}.{string.Join(".", model.ContainingTypes.Select(t => t.Name))}.{model.MethodName}.g.cs",
			SourceText.From(sb.ToString(), Encoding.UTF8)
		);
	}
}

// Models (plain records are fine here, no Roslyn types)
record MethodModel()
{
	public string Namespace { get; set; } = string.Empty;

	public string ClassName { get; set; } = string.Empty;

	public ContainingType[] ContainingTypes { get; set; } = [];

	public string MethodName { get; set; } = string.Empty;

	public string Message { get; set; } = string.Empty;

	public int LogLevel { get; set; }

	public ParameterModel[] Parameters { get; set; } = [];

	public string ReturnType { get; set; } = string.Empty;

}

record ContainingType
{
	public string Name { get; set; } = string.Empty;

	public string Kind { get; set; } = string.Empty;

	public ContainingType(string name, string kind) =>
		(Name, Kind) = (name, kind);
}

record ParameterModel()
{
	public string Type { get; set; } = string.Empty;

	public string Name { get; set; } = string.Empty;

	public static ParameterModel Create(IParameterSymbol p) =>
		new()
		{
			Type = p.Type.ToDisplayString(),
			Name = p.Name
		};
}
