// Wrap: Functional Monads for .NET
// Copyright (c) bfren - licensed under https://mit.bfren.dev/2019

using System.Collections.Generic;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace Wrap;

/// <summary>
/// Source generator for FailureValue objects.
/// </summary>
[Generator]
public sealed class FailureValueGenerator : IIncrementalGenerator
{
	/// <inheritdoc/>
	public void Initialize(IncrementalGeneratorInitializationContext context)
	{
		// Filter to methods decorated with [Failure]
		var methods = context.SyntaxProvider
			.ForAttributeWithMetadataName(
				"Wrap.FailureAttribute",
				predicate: static (node, _) => node is MethodDeclarationSyntax,
				transform: static (ctx, _) => GetMethod(ctx))
			.Where(static m => m is not null);

		// Register output
		context.RegisterSourceOutput(methods, Execute);
	}

	private static MethodModel? GetMethod(GeneratorAttributeSyntaxContext ctx)
	{
		if (ctx.TargetSymbol is not IMethodSymbol method)
		{
			return null;
		}

		// Get key values from attribute
		var attr = ctx.Attributes[0];
		var message = attr.ConstructorArguments[0].Value switch
		{
			string x =>
				x,

			_ =>
				string.Empty
		};
		var logLevel = (attr.ConstructorArguments.Length > 1) switch
		{
			true when attr.ConstructorArguments[1].Value is int x =>
				x,

			_ =>
				0
		};

		// Walk up ContainingType chain, collecting outermost → innermost
		var containingTypes = new Stack<ContainingType>();
		var current = method.ContainingType;
		while (current is not null)
		{
			// Record types are not exposed as TypeKind
			var isRecord = current.DeclaringSyntaxReferences
				.Select(r => r.GetSyntax())
				.OfType<TypeDeclarationSyntax>()
				.Any(s => s.IsKind(SyntaxKind.RecordDeclaration) || s.IsKind(SyntaxKind.RecordStructDeclaration));

			// Get the current type
			var kind = current.TypeKind switch
			{
				TypeKind.Struct =>
					"struct",

				_ when isRecord =>
					"record",

				_ =>
					"class"
			};

			containingTypes.Push(new(current.Name, kind));
			current = current.ContainingType; // null when we reach the namespace
		}

		// Create model
		return new MethodModel
		{
			Namespace = method.ContainingType.ContainingNamespace.ToDisplayString(),
			ClassName = method.ContainingType.Name,
			ContainingTypes = [.. containingTypes],
			MethodName = method.Name,
			Message = message,
			LogLevel = logLevel,
			Parameters = [.. method.Parameters.Select(ParameterModel.Create)],
			ReturnType = method.ReturnType.ToDisplayString()
		};
	}

	private static void Execute(SourceProductionContext ctx, MethodModel? model)
	{
		// Handle null
		if (model == null)
		{
			return;
		}

		// Build lists of parameters and arguments
		var paramList = string.Join(", ", model.Parameters.Select(p => $"{p.Type} {p.Name}"));
		var argList = (model.Parameters.Length > 0) switch
		{
			true =>
				", " + string.Join(", ", model.Parameters.Select(p => p.Name)),

			false =>
				""
		};

		// Build file header
		var sb = new StringBuilder()
			.AppendLine("// <auto-generated/>")
			.AppendLine("#nullable enable")
			.AppendLine()
			.AppendLine($"namespace {model.Namespace};")
			.AppendLine();

		// Open each containing type and add intended
		for (var i = 0; i < model.ContainingTypes.Length; i++)
		{
			var indentOpen = new string(' ', 4 * i);
			var type = model.ContainingTypes[i];
			_ = sb.AppendLine($"{indentOpen}partial {type.Kind} {type.Name}")
				.AppendLine($"{indentOpen}{{");
		}

		// Indent the method body one level per nesting depth
		var indent = new string(' ', model.ContainingTypes.Length * 4);

		_ = sb.AppendLine($"{indent}public static partial {model.ReturnType} {model.MethodName}({paramList})")
			.AppendLine($"{indent}{{")
			.AppendLine($"{indent}    var message = $\"{model.Message.TrimEnd('.')}.\";")
			.AppendLine($"{indent}    var context = \"{model.ClassName}.{model.MethodName}()\";")
			.AppendLine($"{indent}    return new {model.ReturnType}(message{argList})")
			.AppendLine($"{indent}    {{")
			.AppendLine($"{indent}        Level = (Wrap.Logging.LogLevel){model.LogLevel},")
			.AppendLine($"{indent}        Context = context")
			.AppendLine($"{indent}    }};")
			.AppendLine($"{indent}}}");

		// Close each containing type in reverse
		for (var i = model.ContainingTypes.Length - 1; i >= 0; i--)
		{
			var indentClose = new string(' ', 4 * i);
			_ = sb.AppendLine($"{indentClose}}}");
		}

		// Add source file
		ctx.AddSource(
			$"{model.Namespace}.{string.Join(".", model.ContainingTypes.Select(t => t.Name))}.{model.MethodName}.g.cs",
			SourceText.From(sb.ToString(), Encoding.UTF8)
		);
	}
}
