// Wrap: .NET monads for functional style.
// Copyright (c) bfren - licensed under https://mit.bfren.dev/2019

using System;
using System.Threading.Tasks;

namespace Wrap.Extensions;

public static partial class MaybeExtensions
{
	/// <summary>
	/// Return a value determined by the value of <paramref name="this"/> and the result of <paramref name="predicate"/>.
	/// </summary>
	/// <typeparam name="T">Ok value type.</typeparam>
	/// <typeparam name="TReturn">Return value type.</typeparam>
	/// <param name="this">Maybe object.</param>
	/// <param name="predicate">Uses value of <paramref name="this"/> to determines whether <paramref name="someFalse"/> or <paramref name="someTrue"/> should be used.</param>
	/// <param name="someFalse">Used if <paramref name="this"/> is <see cref="Some{T}"/> and <paramref name="predicate"/> returns <see langword="false"/>.</param>
	/// <param name="someTrue">Used if <paramref name="this"/> is <see cref="Some{T}"/> and <paramref name="predicate"/> returns <see langword="true"/>.</param>
	/// <returns>Value generated by<paramref name="someFalse"/> or <paramref name="someTrue"/>.</returns>
	public static Maybe<TReturn> If<T, TReturn>(this Maybe<T> @this, Func<T, bool> predicate, Func<T, Maybe<TReturn>> someTrue, Func<T, Maybe<TReturn>> someFalse) =>
		Bind(@this,
			x => predicate(x) switch
			{
				false =>
					someFalse(x),

				true =>
					someTrue(x)
			}
		);

	/// <inheritdoc cref="If{T, TReturn}(Maybe{T}, Func{T, bool}, Func{T, Maybe{TReturn}}, Func{T, Maybe{TReturn}})"/>
	public static Task<Maybe<TReturn>> IfAsync<T, TReturn>(this Maybe<T> @this, Func<T, bool> predicate, Func<T, Task<Maybe<TReturn>>> someTrue, Func<T, Task<Maybe<TReturn>>> someFalse) =>
		BindAsync(@this,
			x => predicate(x) switch
			{
				false =>
					someFalse(x),

				true =>
					someTrue(x)
			}
		);

	/// <inheritdoc cref="If{T, TReturn}(Maybe{T}, Func{T, bool}, Func{T, Maybe{TReturn}}, Func{T, Maybe{TReturn}})"/>
	public static Task<Maybe<TReturn>> IfAsync<T, TReturn>(this Task<Maybe<T>> @this, Func<T, bool> predicate, Func<T, Maybe<TReturn>> someTrue, Func<T, Maybe<TReturn>> someFalse) =>
		BindAsync(@this,
			x => predicate(x) switch
			{
				false =>
					someFalse(x),

				true =>
					someTrue(x)
			}
		);

	/// <inheritdoc cref="If{T, TReturn}(Maybe{T}, Func{T, bool}, Func{T, Maybe{TReturn}}, Func{T, Maybe{TReturn}})"/>
	public static Task<Maybe<TReturn>> IfAsync<T, TReturn>(this Task<Maybe<T>> @this, Func<T, bool> predicate, Func<T, Task<Maybe<TReturn>>> someTrue, Func<T, Task<Maybe<TReturn>>> someFalse) =>
		BindAsync(@this,
			x => predicate(x) switch
			{
				false =>
					someFalse(x),

				true =>
					someTrue(x)
			}
		);
}
